### ISSUE TITLE
Smart Card Connector No Longer Supported

### ISSUE THREAD

**Issue by scottagt** [GoogleChromeLabs/chromeos_smart_card_connector#842]
Hi, I'm getting a Chrome error saying that old apps since December 2022 are no longer supported and Chrome prompts me to uninstall the extension. What am I doing wrong?

**Comment by emaxx-google** [comment]
Hello, are you using ChromeOS or do you have a Windows/Mac/Linux laptop?

**Comment by scottagt** [comment]
Google Chrome web browser (it appears in Chrome extension store, which is how I found it and Chrome browser installed it with no issue)

**Comment by emaxx-google** [comment]
The Smart Card Connector app is only intended to be used on Chromebooks.

We don't forbid installing it on other platforms because some developers are able to use it after special setup, but this was never officially supported for end users. With the Chrome Apps platform deprecation, this will gradually become impossible at all.

I think at some point we want to update our WebStore entry to officially state "ChromeOS only". In the meantime, feel free to ignore the error or uninstall it from your non-Chromebook devices.
